append_text: ''
computer: localhost
default_calc_job_plugin: cp2k
description: ''
filepath_executable: /usr/bin/cp2k.psmp
label: cp2k
prepend_text: export VECLIB_MAXIMUM_THREADS=1
use_double_quotes: 'False'
