append_text: ' '
computer: localhost
default_calc_job_plugin: critic2
description: critic2 at daint alps
filepath_executable: /usr/local/bin/critic2
label: critic2
prepend_text: ''
use_double_quotes: 'False'
