append_text: ' '
computer: localhost
default_calc_job_plugin: critic2
description: critic2 at daint alps
filepath_executable: /home/jovyan/opt/critic2/build/src/critic2
label: critic2
prepend_text: ''
use_double_quotes: 'False'
