label: "stm-n"
description: "stm code from https://github.com/nanotech-empa/cp2k-spm-tools.git"
default_calc_job_plugin: "nanotech_empa.stm"
filepath_executable: "/opt/conda/bin/cp2k-stm-sts-wfn"
computer: "localhost"
prepend_text: " "
append_text: " "
use_double_quotes: "False"
